version: 2

models:

  - name: stg_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null

  - name: fact_transactions
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: merchant_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_merchants')
              field: merchant_id
      - name: amount
        tests:
          - not_null
          - custom_amount_non_negative
      - name: currency
        tests:
          - relationships:
              to: ref('dim_currency')
              field: currency_code
          - custom_valid_currency_code

  - name: fact_fraud_signals
    columns:
      - name: transaction_id
        tests:
          - not_null
          - relationships:
              to: ref('fact_transactions')
              field: transaction_id
