version: 2

models:

  - name: stg_transactions
    tests:
      - not_null:
          column_name: transaction_id

  - name: fact_transactions
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null

      - name: amount
        tests:
          - not_null

  - name: fact_fraud_signals
    columns:
      - name: transaction_id
        tests:
          - not_null

  - name: fact_settlement_daily
    columns:
      - name: merchant_id
        tests:
          - not_null

      - name: gross_amount
        tests:
          - dbt_utils.expression_is_true:
              expression: "gross_amount >= 0"
  - name: fact_fraud_settlement_daily
    columns:
      - name: merchant_id
        tests:
          - not_null
      
      - name: fraud_date
        tests:
          - not_null
      
      - name: fraud_amount
        tests:
          - dbt_utils.expression_is_true:
              expression: "fraud_amount >= 0"
